
server:
  port: 8082

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
  flyway:
    baselineOnMigrate: true
    validateMigrationNaming: true
  jpa:
    show-sql: true
