
server:
  port: 8082

spring:
  application:
    name: "customers"
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8084/

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
  flyway:
    baselineOnMigrate: true
    validateMigrationNaming: true
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

info:
  app:
    name: ${spring.application.name}
    description: My-car Customers Application
    version: "v0.0.1"
