
server:
  port: 8082

spring:
  application:
    name: "customers"
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8084/

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: oracle
  flyway:
    baselineOnMigrate: true
    validateMigrationNaming: true
  jpa:
    show-sql: true
