
server:
  port: 8086

spring:
  application:
    name: gatewayserver
  config:
    import: optional:configserver:http://localhost:8084/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Eureka server will share microservices data with Gateway
          lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true

  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: My-car Gateway Application
    version: "v0.0.1"
