
logging:
  level:
    org:
      kent0k:
        sshextractor: DEBUG

spring:
  application:
    name: 'sshextractor'

ssh-extractor:
  os-ssh-folder-name: '.ssh'
  project-ssh-folder-name: 'ssh_keys'
  thread-timeout: 30
