
services:

  configserver-container:
    image: kent0k/my-car-configserver:${DOCKER_IMAGE_TAG_VALUE}
    container_name: configserver-container
    ports:
      - 8084:8084
    networks:
      - mycarsharednetwork
    volumes:
      - ssh-volume:/root/.ssh
    healthcheck:
      test: "curl --fail --silent localhost:8084/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: rabbitmq-spring-app
    depends_on:
      rabbit-container:
        condition: service_healthy

  eurekaserver-container:
    image: kent0k/my-car-eurekaserver:${DOCKER_IMAGE_TAG_VALUE}
    container_name: eurekaserver-container
    ports:
      - 8085:8085
    healthcheck:
      test: "curl --fail --silent localhost:8085/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_RABBITMQ_HOST: rabbitmq-spring-app
      SPRING_CONFIG_IMPORT: configserver:http://configserver-container:8084
    networks:
      - mycarsharednetwork
    depends_on:
      configserver-container:
        condition: service_healthy

  gatewayserver-container:
    image: kent0k/my-car-gatewayserver:${DOCKER_IMAGE_TAG_VALUE}
    container_name: gatewayserver-container
    ports:
      - 8086:8086
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver-container:8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-container:8085/eureka
    networks:
      - mycarsharednetwork
    depends_on:
      cars-container:
        condition: service_healthy
      customers-container:
        condition: service_healthy
      servicepartners-container:
        condition: service_healthy
      eurekaserver-container:
        condition: service_healthy
