
server:
  port: 8081

spring:
  application:
    name: "cars"
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8084/

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db-changelog.xml
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

info:
  app:
    name: ${spring.application.name}
    description: My-car Cars Application
    version: "v0.0.1"
