
server:
  port: 8081

spring:
  application:
    name: "cars"
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8084/

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db-changelog.xml
  jpa:
    show-sql: true
