
server:
  port: 8083

spring:
  application:
    name: "servicepartners"
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8084/
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        sendIsReadyCommunication-out-0:
          destination: carmaintenance-message-dto-from-customers-microservice

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      database: admin
      host: localhost
      port: 27017
      username: mongoadmin
      password: bdung

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

info:
  app:
    name: ${spring.application.name}
    description: My-car ServicePartners Application
    version: "v0.0.1"
