
server:
  port: 8087

spring:
  application:
    name: vaadinui
  profiles:
    active: production
  config:
    import: optional:configserver:http://localhost:8084/

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

info:
  app:
    name: ${spring.application.name}
    description: My-car VaadinUI Application
    version: "v0.0.1"
